# Generated by Django 3.0.5 on 2020-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20181112_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:30 - 10:40', '9:30 - 10:40'), ('10:40 - 11:50', '10:40 - 11:50'), ('11:50 - 1:00', '11:50 - 1:00'), ('1:30 - 2:40', '1:30 - 2:40'), ('2:40 - 3:50', '2:40 - 3:50')], default='9:30 - 10:40', max_length=50),
        ),
    ]
